```puml
start
:Command;
:**Read** & **Parse**;
if (Internal?) then (No)
    if (Exist in absolute path) then (Found)
        :**Execute**;
        stop
    elseif (Exist in PATH?) then (Found)
        :**Execute**;
        stop
    else (Not found)
        :**Return** error message;
        end
    endif
else (Yes)
    :**Execute**;
    stop
endif
```