name: CI for OS-Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Shell
        run: make shell
      - name: Archive Shell artifact
        uses: actions/upload-artifact@v2
        with:
          name: shell-artifact
          path: src/shell
    
  Test:
    needs: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Use Shell artifact
        uses: actions/download-artifact@v2
        with:
          name: shell-artifact
      - name: Make shell executable
        run: chmod +x ./shell
      - name: Install python dependencies
        run: make prepare_ci_env
      - name: Run all tests
        run: make ci_test
