name: CI for OS-Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      
    - name: make install_deps
      run: make install_deps
      
    - name: make run_test
      run: make run_test
