name: CI for OS-Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Build Shell
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: shell-artifact
          path: main
    
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: make install_deps
        run: make install_deps
      - uses: actions/download-artifact@v2
        with:
          name: shell-artifact
      - name: make run_test
        run: make run_test
